# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 01:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onedraw',
            fields=[
                ('name', models.CharField(help_text='Twitter アカウントのユーザー名', max_length=30)),
                ('screen_name', models.CharField(help_text='Twitter アカウントの @ユーザー名', max_length=15, primary_key=True, serialize=False)),
                ('work', models.CharField(help_text='ワンドロの対象の作品名', max_length=30)),
                ('genre', models.CharField(help_text='作品内の CP 名など', max_length=30)),
                ('event_day', models.CharField(help_text='開催日 (曜日や週など)', max_length=30)),
                ('rule_url', models.CharField(help_text='ワンドロのルールや注意事項が書かれたページの URL', max_length=300, validators=[django.core.validators.URLValidator])),
                ('rt_screen_name', models.CharField(help_text='参加ツイートをリツイートするアカウント の @ユーザー名', max_length=15)),
                ('langs', multiselectfield.db.fields.MultiSelectField(choices=[('ja', '日本語'), ('ko', '韓国語'), ('cn', '中国語'), ('en', '英語'), ('ar', 'アラビア語'), ('bn', 'ベンガル語'), ('cs', 'チェコ語'), ('da', 'デンマーク語'), ('de', 'ドイツ語'), ('el', 'ギリシア語'), ('es', 'スペイン語'), ('fa', 'ペルシア語'), ('fi', 'フィンランド語'), ('fr', 'フランス語'), ('he', 'ヘブライ語'), ('hi', 'ヒンディー語'), ('hu', 'ハンガリー語'), ('id', 'インドネシア語'), ('it', 'イタリア語'), ('nl', 'オランダ語'), ('no', 'ノルウェー語'), ('pl', 'ポーランド語'), ('pt', 'ポルトガル語'), ('ro', 'ルーマニア語'), ('ru', 'ロシア語'), ('sv', 'スウェーデン語'), ('th', 'タイ語'), ('tr', 'トルコ語'), ('uk', 'ウクライナ語'), ('ur', 'ウルドゥー語'), ('vi', 'ベトナム語')], help_text='対応している言語', max_length=92)),
                ('active', models.BooleanField(default=True, help_text='活動中であるかどうか')),
                ('description', models.TextField(blank=True, help_text='補足説明')),
            ],
        ),
    ]
