# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 01:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedraw_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedraw',
            name='rt_screen_name',
            field=models.CharField(blank=True, help_text='参加ツイートをリツイートするアカウント の @ユーザー名', max_length=15),
        ),
        migrations.AlterField(
            model_name='onedraw',
            name='rule_url',
            field=models.CharField(blank=True, help_text='ワンドロのルールや注意事項が書かれたページの URL', max_length=300, validators=[django.core.validators.URLValidator]),
        ),
    ]
