# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 04:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedraw_links', '0002_auto_20170925_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedraw',
            name='collection_url',
            field=models.CharField(blank=True, help_text='ツイートまとめページの URL', max_length=300, validators=[django.core.validators.URLValidator]),
        ),
    ]
